# Site settings
title:          shiji
description:    "aaaa"
baseurl:        "/"
url:            "https://shiji.meiwenhui.com"

# Author
author:
  name:         shiji

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  # - jekyll-feed
  # - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:title
